### ISSUE TITLE
Convert existing end to end tests to `expect`

### ISSUE THREAD

**Issue by ultimatecoder** [ultimatecoder/programming_challenges#2]
## Description

Existing end to end tests are based on Python hacks. It is a tedious write, run and maintain them. From #emacs at Freenode, `ski` user suggested [expect](https://core.tcl.tk/expect/index). Expect is a utility for writing end to end tests for command line utilities.

## Task

- [ ] Shift existing tests outside the program source folder
- [ ] Convert existing end to end tests with expect testing scripts
    - [ ] Convert end to end tests of "3n Plus 1" problem
    - [ ] Convert end to end tests for "The trip" problem
- [ ] Add description of the tool at the `README` file. Mention the tool in the dependency.

**Comment by ultimatecoder** [comment]
Fixed at #3
